# Generated by Django 4.1.7 on 2023-04-03 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='propertyranges',
            name='price',
            field=models.FloatField(),
        ),
    ]
