# Generated by Django 4.1.6 on 2023-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyranges',
            name='price',
            field=models.FloatField(),
        ),
    ]
