# Generated by Django 4.1.6 on 2023-03-30 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyranges_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
