# Generated by Django 4.1.7 on 2023-04-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_rating_alter_propertyranges_price'),
        ('properties', '0005_remove_property_rating'),
    ]

    operations = [
    ]
