# Generated by Django 4.1.7 on 2023-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_rating_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='preview2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='preview3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
