# Generated by Django 4.1.7 on 2023-04-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_preview2_property_preview3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyranges',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyranges', to='properties.property'),
        ),
    ]
