# Generated by Django 4.1.7 on 2023-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyranges_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='preview2',
            field=models.ImageField(default='house.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='preview3',
            field=models.ImageField(default='house.jpg', null=True, upload_to=''),
        ),
    ]
